name: pub_release
version: 10.0.8
homepage: https://github.com/onepub-dev/pub_release
documentation: https://pubrelease.onepub.dev/
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
publish_to: 'none'
repository: https://github.com/open-runtime/pub_release.git
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.3.1
  dcli:
    git:
      url: https://github.com/open-runtime/dcli.git
      path: dcli
  dcli_core:
    git:
      url: https://github.com/open-runtime/dcli.git
      path: dcli_core
  github: ^9.4.0
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.3
  pub_semver: ^2.1.0
  pubspec_manager: ^1.0.0-alpha.16
  settings_yaml:
    git:
      url: https://github.com/open-runtime/settings_yaml.git
dev_dependencies:
  dependency_validator: ^3.0.0
  lint_hard: ^4.0.0
  test: ^1.24.6
executables:
  pub_release:
  github_release:
  github_workflow_release:
platforms:
  linux:
  windows:
  macos:
