name: pub_release
version: 10.0.8
homepage: https://github.com/onepub-dev/pub_release
documentation: https://pubrelease.onepub.dev/
description: Automates the release of a dart package to pub.dev including running dartfmt, creating a git tag, incrementing the packages version no. and pushing the package to pub.dev.
publish_to: 'none'
repository: https://github.com/open-runtime/pub_release.git
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.5.0
  github: ^9.24.0
  meta: ^1.14.0
  mime: ^1.0.5
  path: ^1.9.0
  pub_semver: ^2.1.4
  pubspec_manager: ^1.0.0
  dcli:
  dcli_core:
  settings_yaml:

dev_dependencies:
  dependency_validator: ^3.2.3
  lint_hard: ^4.0.0
  test: ^1.25.3
executables:
  pub_release:
  github_release:
  github_workflow_release:
platforms:
  linux:
  windows:
  macos:
